//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchSortPaging.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Co2Db_MedarbejderGruppe_Virksomheder_list
    {
        public Nullable<int> mgCompanyID { get; set; }
        public string mgNavn { get; set; }
        public int MedarbejderGruppe_FK { get; set; }
        public int Virksomheder_FK { get; set; }
        public int CompanyID { get; set; }
        public string Cvrnr { get; set; }
        public string Firmanavn { get; set; }
    }
}
