//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchSortPaging.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Co2Db_Company_KundeGrp_VarePris
    {
        public int CompanyID { get; set; }
        public string Cvrnr { get; set; }
        public string Firmanavn { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> KundeGrpID { get; set; }
        public string KundeGrpNavn { get; set; }
        public Nullable<int> VareID { get; set; }
        public Nullable<double> SalgsPris { get; set; }
        public Nullable<double> Rabat { get; set; }
        public Nullable<double> KundePris { get; set; }
        public Nullable<double> FragtGebyr { get; set; }
        public Nullable<System.DateTime> Dato { get; set; }
        public string VareNr { get; set; }
        public string Navn { get; set; }
        public Nullable<int> VareGrpID { get; set; }
        public string VareGrpNr { get; set; }
    }
}
