//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchSortPaging.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Co2Db_MedarbejderGrupper
    {
        public int ID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public string Cvrnr { get; set; }
        public string Firmanavn { get; set; }
        public Nullable<bool> Aktiv { get; set; }
        public string Navn { get; set; }
        public string Brugernavn { get; set; }
        public string Kodeord { get; set; }
        public string Password { get; set; }
        public string IP { get; set; }
        public Nullable<bool> Informationssite { get; set; }
        public Nullable<bool> Administrationssite { get; set; }
        public Nullable<int> Sort { get; set; }
        public Nullable<System.DateTime> Dato { get; set; }
        public string RettetAF { get; set; }
        public Nullable<System.DateTime> RettetDen { get; set; }
        public string RettetIP { get; set; }
    }
}
