//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchSortPaging.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Co2Db_Invoice_TotalInvoicePrice
    {
        public int InvoiceID { get; set; }
        public Nullable<double> TotalSalesPrice { get; set; }
        public Nullable<double> TotalItemPrice { get; set; }
        public Nullable<double> TotalDiscountPrice { get; set; }
        public Nullable<double> InvoiceTotal { get; set; }
        public Nullable<double> InvoiceVAT { get; set; }
        public Nullable<double> InvoiceTotalInclVAT { get; set; }
        public Nullable<double> InvoiceProvision { get; set; }
    }
}
