//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchSortPaging.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Co2Db_AED_Battery_Electrod_List
    {
        public int ID { get; set; }
        public Nullable<int> Status { get; set; }
        public int CompanyID { get; set; }
        public string Firmanavn { get; set; }
        public string SerialNo { get; set; }
        public Nullable<System.DateTime> WarencyExpireDate { get; set; }
        public Nullable<int> BilagStatus { get; set; }
        public Nullable<System.DateTime> BilagModtagetDato { get; set; }
        public string ResponsibleName { get; set; }
        public string ResponsiblePhone { get; set; }
        public string ResponsibleEmail { get; set; }
        public string VareNr { get; set; }
        public string Navn { get; set; }
        public Nullable<int> BatteryID { get; set; }
        public Nullable<int> BatteryStatus { get; set; }
        public string BatteryStatusText { get; set; }
        public string BatteryTypeText { get; set; }
        public Nullable<System.DateTime> BatteryExpireDate { get; set; }
        public Nullable<int> ElectrodID { get; set; }
        public Nullable<int> ElectrodStatus { get; set; }
        public string ElectrodStatusText { get; set; }
        public string ElectrodTypeText { get; set; }
        public Nullable<System.DateTime> ElectrodExpireDate { get; set; }
        public string Adresse1 { get; set; }
        public string Adresse2 { get; set; }
        public string Postnr { get; set; }
        public string Bynavn { get; set; }
        public string Land { get; set; }
    }
}
