//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchSortPaging.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Co2Db_TilbudHospital
    {
        public int thTilbudHospitalID { get; set; }
        public Nullable<int> thStatus { get; set; }
        public Nullable<int> thCompanyID { get; set; }
        public Nullable<System.DateTime> thTilbudsDato { get; set; }
        public Nullable<int> thForfaldsmaade { get; set; }
        public Nullable<System.DateTime> thHovedForfald { get; set; }
        public Nullable<int> thPraemieForhold { get; set; }
        public Nullable<int> thForventetForsikretPersoner { get; set; }
        public Nullable<int> thEksisterendeLeverandor { get; set; }
        public Nullable<int> thForsikringsdaekning { get; set; }
        public Nullable<bool> thForsikringsdaekningStraks { get; set; }
        public Nullable<int> thIndmeldelseTidspunkt { get; set; }
        public Nullable<int> thIndmeldelsestidspunktEfter { get; set; }
        public Nullable<int> thIndmeldelsestidspunktSenestEfter { get; set; }
        public Nullable<int> thOmfattedeMedarbejdere { get; set; }
        public string thOmfattedeMedarbejdereAndet { get; set; }
        public Nullable<int> thTimetalsbegraensning { get; set; }
        public Nullable<int> thTimetalsbegraensningTimer { get; set; }
        public Nullable<int> thSkadestatistik { get; set; }
        public Nullable<int> thOplysningerAKJ { get; set; }
        public Nullable<int> thTilbudRekvireret { get; set; }
        public Nullable<int> thTilbudRekvireretIntern { get; set; }
        public Nullable<int> thTilbudRekvireretMaegler { get; set; }
        public string thAnsvarlig { get; set; }
        public string thKvitteret { get; set; }
        public string thNoter { get; set; }
        public string thRettetAf { get; set; }
        public Nullable<System.DateTime> thRettetDen { get; set; }
        public string thRettetIP { get; set; }
        public Nullable<decimal> thPraemie { get; set; }
    }
}
