//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchSortPaging.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Co2Db_Hospitalforsikring
    {
        public int HospitalsforsikringID { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> MedarbejderGruppeID { get; set; }
        public Nullable<int> LeverandorID { get; set; }
        public Nullable<System.DateTime> Etableringsdato { get; set; }
        public Nullable<int> Forfaldsmaade { get; set; }
        public Nullable<int> HovedForfald { get; set; }
        public Nullable<int> PraemieForhold { get; set; }
        public Nullable<int> PraemieGruppe { get; set; }
        public Nullable<int> Forsikringsdaekning { get; set; }
        public Nullable<bool> ForsikringsdaekningStraks { get; set; }
        public Nullable<int> IndmeldelseTidspunkt { get; set; }
        public Nullable<int> IndmeldelsestidspunktEfter { get; set; }
        public Nullable<int> IndmeldelsestidspunktSenestEfter { get; set; }
        public Nullable<int> OmfattedeMedarbejdere { get; set; }
        public string OmfattedeMedarbejdereAndet { get; set; }
        public Nullable<int> Timetalsbegraensning { get; set; }
        public Nullable<int> TimetalsbegraensningTimer { get; set; }
        public string LeverandorAftaleNr { get; set; }
        public Nullable<int> Risikobonus { get; set; }
        public string Noter { get; set; }
        public string RettetAf { get; set; }
        public Nullable<System.DateTime> RettetDen { get; set; }
        public string RettetIP { get; set; }
        public Nullable<bool> Informationssite { get; set; }
        public Nullable<bool> Administrationssite { get; set; }
    }
}
