//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchSortPaging.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Co2Db_Currency
    {
        public int ID { get; set; }
        public string CurrencyCode { get; set; }
        public string CurrencyDesc { get; set; }
        public Nullable<double> CurrencyRate { get; set; }
        public Nullable<System.DateTime> CurrencyDate { get; set; }
        public string CurrencySymbol { get; set; }
        public string Currency { get; set; }
    }
}
