//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchSortPaging.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Co2Db_Invoice_Stats
    {
        public int InvoiceID { get; set; }
        public Nullable<int> Pos { get; set; }
        public int ID { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<bool> InvoicePaid { get; set; }
        public int CompanyID { get; set; }
        public string Firmanavn { get; set; }
        public string VareVareNr { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<double> SalesPrice { get; set; }
        public Nullable<double> LinePriceTotal { get; set; }
        public Nullable<double> ProvisionRate { get; set; }
        public Nullable<double> Provision { get; set; }
        public Nullable<double> LineProvision { get; set; }
        public string VareNavn { get; set; }
        public string Cvrnr { get; set; }
        public string CvrnrCompany { get; set; }
        public Nullable<System.Guid> AgentID { get; set; }
    }
}
