//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchSortPaging.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Co2Db_Tilbudhospital_Virksomhed
    {
        public int thTilbudHospitalID { get; set; }
        public Nullable<int> thStatus { get; set; }
        public Nullable<int> thCompanyID { get; set; }
        public Nullable<System.DateTime> thTilbudsDato { get; set; }
        public Nullable<int> thForfaldsmaade { get; set; }
        public Nullable<System.DateTime> thHovedForfald { get; set; }
        public Nullable<int> thPraemieForhold { get; set; }
        public Nullable<int> thForventetForsikretPersoner { get; set; }
        public Nullable<int> thEksisterendeLeverandor { get; set; }
        public Nullable<int> thForsikringsdaekning { get; set; }
        public Nullable<bool> thForsikringsdaekningStraks { get; set; }
        public Nullable<int> thIndmeldelseTidspunkt { get; set; }
        public Nullable<int> thIndmeldelsestidspunktEfter { get; set; }
        public Nullable<int> thIndmeldelsestidspunktSenestEfter { get; set; }
        public Nullable<int> thOmfattedeMedarbejdere { get; set; }
        public string thOmfattedeMedarbejdereAndet { get; set; }
        public Nullable<int> thTimetalsbegraensning { get; set; }
        public Nullable<int> thTimetalsbegraensningTimer { get; set; }
        public Nullable<int> thSkadestatistik { get; set; }
        public Nullable<int> thOplysningerAKJ { get; set; }
        public Nullable<int> thTilbudRekvireret { get; set; }
        public Nullable<int> thTilbudRekvireretIntern { get; set; }
        public Nullable<int> thTilbudRekvireretMaegler { get; set; }
        public string thAnsvarlig { get; set; }
        public string thKvitteret { get; set; }
        public string thNoter { get; set; }
        public string thRettetAf { get; set; }
        public Nullable<System.DateTime> thRettetDen { get; set; }
        public string thRettetIP { get; set; }
        public Nullable<decimal> thPraemie { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<bool> Historik { get; set; }
        public Nullable<int> ProfileType { get; set; }
        public string Cvrnr { get; set; }
        public string Firmanavn { get; set; }
        public string Adresse1 { get; set; }
        public string Adresse2 { get; set; }
        public string Postnr { get; set; }
        public string Bynavn { get; set; }
        public string State { get; set; }
        public Nullable<int> LandekodeID { get; set; }
        public Nullable<int> FirmastatusID { get; set; }
        public Nullable<int> AndetID { get; set; }
        public Nullable<int> SamArbejdspartner { get; set; }
        public string Telefon { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string WebSiteUrl { get; set; }
        public string Noter { get; set; }
        public string BeslutNavn { get; set; }
        public string BeslutStilling { get; set; }
        public string BeslutTelefon { get; set; }
        public string BeslutMobil { get; set; }
        public string BeslutEmail { get; set; }
        public string AdminNavn { get; set; }
        public string AdminStilling { get; set; }
        public string AdminTelefon { get; set; }
        public string AdminMobil { get; set; }
        public string AdminEmail { get; set; }
        public Nullable<int> KundeStatusID { get; set; }
        public Nullable<System.DateTime> Ophortdato { get; set; }
        public Nullable<int> BetjeningsansvarligID { get; set; }
        public Nullable<int> AfdelingAPID { get; set; }
        public Nullable<int> DagligBetjenerAPID { get; set; }
        public Nullable<int> KontaktansvarligAPID { get; set; }
        public Nullable<int> SelskabID { get; set; }
        public Nullable<int> DagligBetjenerEksternID { get; set; }
        public Nullable<int> KontaktansvarligEksternID { get; set; }
        public string RettetAf { get; set; }
        public string RettetIP { get; set; }
        public Nullable<System.DateTime> RettetDen { get; set; }
        public string OprettetAf { get; set; }
        public string OprettetIP { get; set; }
        public Nullable<System.DateTime> OprettetDen { get; set; }
        public Nullable<bool> MedlemDanskErhverv { get; set; }
        public Nullable<bool> MedlemGLSA { get; set; }
        public Nullable<int> BrancheForeningID { get; set; }
        public Nullable<int> ParentID { get; set; }
    }
}
