//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchSortPaging.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Co2Db_Postnr
    {
        public int ID { get; set; }
        public string Postnr { get; set; }
        public string Bynavn { get; set; }
        public string Gade { get; set; }
        public string Firma { get; set; }
        public Nullable<int> LandID { get; set; }
        public Nullable<bool> Provins { get; set; }
        public string Land { get; set; }
    }
}
