//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchSortPaging.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Co2Db_Logline
    {
        public int ID { get; set; }
        public string Status { get; set; }
        public string Metode { get; set; }
        public string LogText { get; set; }
        public string ClientInfo { get; set; }
        public string Cvrnr { get; set; }
        public Nullable<int> LogType { get; set; }
        public string OprettetAf { get; set; }
        public Nullable<System.DateTime> OprettetDen { get; set; }
        public string OprettetIP { get; set; }
    }
}
