//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchSortPaging.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Co2Db_VareGrp
    {
        public int ID { get; set; }
        public int ParentID { get; set; }
        public string VareGrpNr { get; set; }
        public string VareGrpTekst { get; set; }
        public string Alias { get; set; }
    }
}
